/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description メール・パスワード認証を行い、httpOnly CookieにJWTを設定する。
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Cookieを削除してログアウトする。
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description 現在のログインユーザー情報を返す。
         */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Reports
         * @description 日報一覧を取得する。
         */
        get: operations["get_reports_api_v1_reports_get"];
        put?: never;
        /**
         * Create Report
         * @description 日報を作成する。
         */
        post: operations["create_report_api_v1_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description 日報詳細を取得する。
         */
        get: operations["get_report_api_v1_reports__report_id__get"];
        /**
         * Update Report
         * @description 日報を更新する。
         */
        put: operations["update_report_api_v1_reports__report_id__put"];
        post?: never;
        /**
         * Delete Report
         * @description 日報を削除する。
         */
        delete: operations["delete_report_api_v1_reports__report_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Submit Report
         * @description 日報を提出する（DRAFT → SUBMITTED）。
         */
        patch: operations["submit_report_api_v1_reports__report_id__submit_patch"];
        trace?: never;
    };
    "/api/v1/reports/{report_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Review Report
         * @description 日報を確認済みにする（SUBMITTED → REVIEWED）。
         */
        patch: operations["review_report_api_v1_reports__report_id__review_patch"];
        trace?: never;
    };
    "/api/v1/reports/{report_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Comment
         * @description コメントを投稿する。
         */
        post: operations["create_comment_api_v1_reports__report_id__comments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Customers
         * @description 顧客一覧を取得する。
         */
        get: operations["get_customers_api_v1_customers_get"];
        put?: never;
        /**
         * Create Customer
         * @description 顧客を登録する。
         */
        post: operations["create_customer_api_v1_customers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Customer
         * @description 顧客詳細を取得する。
         */
        get: operations["get_customer_api_v1_customers__customer_id__get"];
        /**
         * Update Customer
         * @description 顧客を更新する。
         */
        put: operations["update_customer_api_v1_customers__customer_id__put"];
        post?: never;
        /**
         * Delete Customer
         * @description 顧客を削除する。
         */
        delete: operations["delete_customer_api_v1_customers__customer_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Users
         * @description ユーザー一覧を取得する。MANAGERのみアクセス可能。
         */
        get: operations["get_users_api_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CommentCreateRequest
         * @description コメント投稿リクエスト。
         */
        CommentCreateRequest: {
            /**
             * Target
             * @description コメント対象（PROBLEM / PLAN）
             */
            target: string;
            /**
             * Content
             * @description コメント内容
             */
            content: string;
        };
        /**
         * CommentCreateResponse
         * @description コメント投稿レスポンス。
         */
        CommentCreateResponse: {
            /** Id */
            id: number;
            /** Target */
            target: string;
            manager: components["schemas"]["SalespersonResponse"];
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CommentResponse
         * @description コメントレスポンス。
         */
        CommentResponse: {
            /** Id */
            id: number;
            /** Target */
            target: string;
            manager: components["schemas"]["SalespersonResponse"];
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CustomerCreateRequest
         * @description 顧客登録リクエスト。
         */
        CustomerCreateRequest: {
            /**
             * Company Name
             * @description 会社名
             */
            company_name: string;
            /**
             * Contact Name
             * @description 担当者名
             */
            contact_name: string;
            /**
             * Address
             * @description 住所
             */
            address?: string | null;
            /**
             * Phone
             * @description 電話番号
             */
            phone?: string | null;
            /**
             * Email
             * @description メールアドレス
             */
            email?: string | null;
        };
        /**
         * CustomerDetailResponse
         * @description 顧客の詳細レスポンス（詳細用）。
         */
        CustomerDetailResponse: {
            /** Id */
            id: number;
            /** Company Name */
            company_name: string;
            /** Contact Name */
            contact_name: string;
        };
        /**
         * CustomerResponse
         * @description 顧客レスポンス。
         */
        CustomerResponse: {
            /** Id */
            id: number;
            /** Company Name */
            company_name: string;
            /** Contact Name */
            contact_name: string;
            /** Address */
            address?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CustomerSummaryResponse
         * @description 顧客の簡易レスポンス（一覧用）。
         */
        CustomerSummaryResponse: {
            /** Id */
            id: number;
            /** Company Name */
            company_name: string;
        };
        /**
         * CustomerUpdateRequest
         * @description 顧客更新リクエスト。
         */
        CustomerUpdateRequest: {
            /**
             * Company Name
             * @description 会社名
             */
            company_name: string;
            /**
             * Contact Name
             * @description 担当者名
             */
            contact_name: string;
            /**
             * Address
             * @description 住所
             */
            address?: string | null;
            /**
             * Phone
             * @description 電話番号
             */
            phone?: string | null;
            /**
             * Email
             * @description メールアドレス
             */
            email?: string | null;
        };
        /** DataResponse[CommentCreateResponse] */
        DataResponse_CommentCreateResponse_: {
            data: components["schemas"]["CommentCreateResponse"];
        };
        /** DataResponse[CustomerResponse] */
        DataResponse_CustomerResponse_: {
            data: components["schemas"]["CustomerResponse"];
        };
        /** DataResponse[LoginResponse] */
        DataResponse_LoginResponse_: {
            data: components["schemas"]["LoginResponse"];
        };
        /** DataResponse[ReportCreateUpdateResponse] */
        DataResponse_ReportCreateUpdateResponse_: {
            data: components["schemas"]["ReportCreateUpdateResponse"];
        };
        /** DataResponse[ReportDetailResponse] */
        DataResponse_ReportDetailResponse_: {
            data: components["schemas"]["ReportDetailResponse"];
        };
        /** DataResponse[ReportReviewResponse] */
        DataResponse_ReportReviewResponse_: {
            data: components["schemas"]["ReportReviewResponse"];
        };
        /** DataResponse[ReportSubmitResponse] */
        DataResponse_ReportSubmitResponse_: {
            data: components["schemas"]["ReportSubmitResponse"];
        };
        /** DataResponse[UserResponse] */
        DataResponse_UserResponse_: {
            data: components["schemas"]["UserResponse"];
        };
        /** DataResponse[list[UserListItemResponse]] */
        DataResponse_list_UserListItemResponse__: {
            /** Data */
            data: components["schemas"]["UserListItemResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description ログインリクエスト。
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             * @description メールアドレス
             */
            email: string;
            /**
             * Password
             * @description パスワード
             */
            password: string;
        };
        /**
         * LoginResponse
         * @description ログインレスポンス。Cookie認証のためtokenは含まない。
         */
        LoginResponse: {
            user: components["schemas"]["UserResponse"];
        };
        /**
         * ReportCreateRequest
         * @description 日報作成リクエスト。
         */
        ReportCreateRequest: {
            /**
             * Report Date
             * Format: date
             * @description 報告日
             */
            report_date: string;
            /**
             * Problem
             * @description 課題・相談
             */
            problem?: string | null;
            /**
             * Plan
             * @description 明日やること
             */
            plan?: string | null;
            /**
             * Status
             * @description ステータス（DRAFT / SUBMITTED）
             */
            status: string;
            /**
             * Visit Records
             * @description 訪問記録
             */
            visit_records?: components["schemas"]["VisitRecordRequest"][];
        };
        /**
         * ReportCreateUpdateResponse
         * @description 日報作成・更新レスポンス。
         */
        ReportCreateUpdateResponse: {
            /** Id */
            id: number;
            /**
             * Report Date
             * Format: date
             */
            report_date: string;
            salesperson: components["schemas"]["SalespersonResponse"];
            /** Problem */
            problem: string | null;
            /** Plan */
            plan: string | null;
            /** Status */
            status: string;
            /** Submitted At */
            submitted_at: string | null;
            /** Visit Records */
            visit_records: components["schemas"]["VisitRecordSummaryResponse"][];
            /** Comments */
            comments: components["schemas"]["CommentResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ReportDetailResponse
         * @description 日報詳細レスポンス。
         */
        ReportDetailResponse: {
            /** Id */
            id: number;
            /**
             * Report Date
             * Format: date
             */
            report_date: string;
            salesperson: components["schemas"]["SalespersonResponse"];
            /** Problem */
            problem: string | null;
            /** Plan */
            plan: string | null;
            /** Status */
            status: string;
            /** Submitted At */
            submitted_at: string | null;
            /** Visit Records */
            visit_records: components["schemas"]["VisitRecordDetailResponse"][];
            /** Comments */
            comments: components["schemas"]["CommentResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ReportReviewResponse
         * @description 日報確認済みレスポンス。
         */
        ReportReviewResponse: {
            /** Id */
            id: number;
            /** Status */
            status: string;
        };
        /**
         * ReportSubmitResponse
         * @description 日報提出レスポンス。
         */
        ReportSubmitResponse: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
        };
        /**
         * ReportUpdateRequest
         * @description 日報更新リクエスト。
         */
        ReportUpdateRequest: {
            /**
             * Report Date
             * Format: date
             * @description 報告日
             */
            report_date: string;
            /**
             * Problem
             * @description 課題・相談
             */
            problem?: string | null;
            /**
             * Plan
             * @description 明日やること
             */
            plan?: string | null;
            /**
             * Status
             * @description ステータス（DRAFT / SUBMITTED）
             */
            status: string;
            /**
             * Visit Records
             * @description 訪問記録
             */
            visit_records?: components["schemas"]["VisitRecordRequest"][];
        };
        /**
         * SalespersonResponse
         * @description 担当者の簡易レスポンス。
         */
        SalespersonResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * UserListItemResponse
         * @description ユーザー一覧の1件分のレスポンス。
         */
        UserListItemResponse: {
            /**
             * Id
             * @description ユーザーID
             */
            id: number;
            /**
             * Name
             * @description 氏名
             */
            name: string;
            /**
             * Email
             * @description メールアドレス
             */
            email: string;
            /**
             * Role
             * @description ロール（SALES / MANAGER）
             */
            role: string;
        };
        /**
         * UserResponse
         * @description ユーザー情報のレスポンス。
         */
        UserResponse: {
            /**
             * Id
             * @description ユーザーID
             */
            id: number;
            /**
             * Name
             * @description 氏名
             */
            name: string;
            /**
             * Email
             * @description メールアドレス
             */
            email: string;
            /**
             * Role
             * @description ロール（SALES / MANAGER）
             */
            role: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "SALES" | "MANAGER";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VisitRecordDetailResponse
         * @description 訪問記録レスポンス（詳細取得時）。
         */
        VisitRecordDetailResponse: {
            /** Id */
            id: number;
            customer: components["schemas"]["CustomerDetailResponse"];
            /** Visit Content */
            visit_content: string;
            /**
             * Visited At
             * @description 訪問時刻（HH:mm）
             */
            visited_at: string;
            /** Visit Order */
            visit_order: number;
        };
        /**
         * VisitRecordRequest
         * @description 訪問記録のリクエスト。
         */
        VisitRecordRequest: {
            /**
             * Customer Id
             * @description 顧客ID
             */
            customer_id: number;
            /**
             * Visit Content
             * @description 訪問内容
             */
            visit_content: string;
            /**
             * Visited At
             * @description 訪問時刻（HH:mm）
             */
            visited_at: string;
        };
        /**
         * VisitRecordSummaryResponse
         * @description 訪問記録レスポンス（作成・更新時）。
         */
        VisitRecordSummaryResponse: {
            /** Id */
            id: number;
            customer: components["schemas"]["CustomerSummaryResponse"];
            /** Visit Content */
            visit_content: string;
            /**
             * Visited At
             * @description 訪問時刻（HH:mm）
             */
            visited_at: string;
            /** Visit Order */
            visit_order: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_LoginResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_UserResponse_"];
                };
            };
        };
    };
    get_reports_api_v1_reports_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                salesperson_id?: number | null;
                status?: string | null;
                sort?: string;
                order?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_api_v1_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ReportCreateUpdateResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ReportDetailResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_report_api_v1_reports__report_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ReportCreateUpdateResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_report_api_v1_reports__report_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_report_api_v1_reports__report_id__submit_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ReportSubmitResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_report_api_v1_reports__report_id__review_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_ReportReviewResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_comment_api_v1_reports__report_id__comments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_CommentCreateResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customers_api_v1_customers_get: {
        parameters: {
            query?: {
                company_name?: string | null;
                contact_name?: string | null;
                sort?: string;
                order?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_customer_api_v1_customers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_CustomerResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_api_v1_customers__customer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_CustomerResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_customer_api_v1_customers__customer_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_CustomerResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_customer_api_v1_customers__customer_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_users_api_v1_users_get: {
        parameters: {
            query?: {
                role?: components["schemas"]["UserRole"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse_list_UserListItemResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
